+ [0] -> 0hill

=== 0hill ===
YOU>>I wonder what's in these drawers?
Hmm, this one's empty...
So is this one...
This one too...
Oh! There's something in this last one!
Let's see... It looks like a sticky note...?
But part of it is torn off...
I can still make a few words out though...
..."Hylox Hill"...
..."on top"...
I wonder what's on top of Hylox Hill...
Or what "Hylox Hill" is in the first place...
Well wherever it is, it's gotta be somewhere nearby!

-> END