+ [0] -> 0red_tree

=== 0red_tree ===
YOU>>What's this...?
The writing's so small, I can barely tell what it says...
Hmm...
...
It seems to say "red tree"...
...and..."near sign"...?
A red tree near a sign, I guess...?
Did I pass by one at some point...?
Better go outside and check...

-> END